LANGUAGES = {
    'RU': {
        'title': 'STORM TRANSLATOR 0.9.0',
        'engine_label': 'Движок перевода',
        'ocr_engine_label': 'Движок OCR',
        'ocr_win_hint': 'WindowsOCR (обычные шрифты)',
        'ocr_paddle_hint': 'PaddleOCR (игровые шрифты)',
        'ocr_easy_hint': 'EasyOCR (пиксельные шрифты)',
        'ocr_multi_hint': 'MultiOCR (все движки)',
        'ocr_fast_hint': 'FastOCR (макс. скорость)',
        'ocr_tesseract_hint': 'Tesseract (пиксельные шрифты)',
        'gpu_status_cuda': 'GPU: CUDA ✓',
        'gpu_status_mps': 'GPU: MPS ✓',
        'gpu_status_cpu': 'GPU: Нет (CPU)',
        'no_text_found': 'Текст не обнаружен',
        'lang_selection': 'Язык интерфейса',
        'src_lang': 'С какого языка',
        'target_lang': 'На какой язык',
        'theme_label': 'Тема оформления',
        'silent_mode': 'Тихий режим',
        'aggregate': 'Агрегация',
        'auto_update': 'Авто-обновление',
        'select_area': 'Выбрать область',
        'areas_count': 'Области перевода',
        'exclusion_zones': 'Зоны исключения',
        'exclusion_zone_label': 'ЗОНА ИСКЛЮЧЕНИЯ',
        'exclusion_list_empty': 'Зоны исключения не выбраны',
        'start_btn': 'АВТО-ПЕРЕВОД',
        'stop_btn': 'ОСТАНОВИТЬ',
        'area_set': 'ОБЛАСТЬ {idx} добавлена!',
        'area_deleted': 'ОБЛАСТЬ {idx} удалена!',
        'area_label': 'ОБЛАСТЬ',
        'exclusion_set': 'Зоны исключения',
        'exclusion_added': 'Зона исключения добавлена.',
        'exclusion_deleted': 'Зона исключения {idx} удалена.',
        'one_time_translate': 'Ручной перевод...',
        'results_panel': 'Перевод',
        'interval_label': 'Интервал (сек):',
        'area_header': 'ОБЛАСТЬ {idx} ({engine})',
        'manage_areas': 'Управление областями',
        'areas_list_empty': 'Области не выбраны',
        'delete': 'Удалить',
        'pin_label': 'Закрепить окно',
        'opacity_label': 'Прозрачность',
        'translate_now': 'РУЧНОЙ ЗАПУСК',
        'clear_btn': 'РУЧНОЕ ОТКЛЮЧЕНИЕ',
        'update_found': 'Доступно обновление!',
        'update_msg': 'Текущая версия: {curr}\nНовая версия: {new}\nОбновить сейчас?',
        'updating': 'Обновление... Приложение будет перезапущено.',
        'languages': {
            'Russian': 'Русский',
            'English': 'Английский',
            'Japanese': 'Японский',
            'Chinese': 'Китайский',
            'Korean': 'Корейский',
            'German': 'Немецкий',
            'French': 'Французский',
            'Auto': 'Авто'
        }
    },
    'EN': {
        'title': 'STORM TRANSLATOR 0.9.0',
        'engine_label': 'Translation Engine',
        'ocr_engine_label': 'OCR Engine',
        'ocr_win_hint': 'WindowsOCR (normal fonts)',
        'ocr_paddle_hint': 'PaddleOCR (game fonts)',
        'ocr_easy_hint': 'EasyOCR (pixel fonts)',
        'ocr_multi_hint': 'MultiOCR (all engines)',
        'ocr_fast_hint': 'FastOCR (max speed)',
        'ocr_tesseract_hint': 'Tesseract (pixel fonts)',
        'gpu_status_cuda': 'GPU: CUDA ✓',
        'gpu_status_mps': 'GPU: MPS ✓',
        'gpu_status_cpu': 'GPU: None (CPU)',
        'no_text_found': 'No text found',

        'lang_selection': 'Interface Language',
        'src_lang': 'Source Language',
        'target_lang': 'Target Language',
        'theme_label': 'Application Theme',
        'pin_label': 'Pin Window',
        'opacity_label': 'Opacity',
        'silent_mode': 'Silent Mode',
        'aggregate': 'Aggregation',
        'auto_update': 'Auto-Update',
        'select_area': 'Select Area',
        'areas_count': 'Capture Areas',
        'exclusion_zones': 'Exclusion Zones',
        'exclusion_zone_label': 'EXCLUSION ZONE',
        'exclusion_list_empty': 'No exclusion zones selected',
        'start_btn': 'AUTO-TRANSLATE',
        'stop_btn': 'STOP',
        'area_set': 'AREA {idx} added!',
        'area_deleted': 'AREA {idx} deleted!',
        'area_label': 'AREA',
        'exclusion_set': 'Exclusion Zones',
        'exclusion_added': 'Exclusion zone added.',
        'exclusion_deleted': 'Exclusion zone {idx} deleted.',
        'one_time_translate': 'One-time translate...',
        'results_panel': 'Translation',
        'interval_label': 'Interval (sec):',
        'area_label': 'AREA',
        'area_header': 'AREA {idx} ({engine})',
        'manage_areas': 'Manage Areas',
        'areas_list_empty': 'No areas selected',
        'delete': 'Delete',
        'translate_now': 'MANUAL START',
        'clear_btn': 'MANUAL CLEAR',
        'update_found': 'Update available!',
        'update_msg': 'Current version: {curr}\nNew version: {new}\nUpdate now?',
        'updating': 'Updating... Application will restart.',
        'languages': {
            'Russian': 'Russian',
            'English': 'English',
            'Japanese': 'Japanese',
            'Chinese': 'Chinese',
            'Korean': 'Korean',
            'German': 'German',
            'French': 'French',
            'Auto': 'Auto'
        }
    }
}
